name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.71.0
  speech_to_text: ^7.0.0
  http: ^1.3.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome_page_logo.png
    - assets/images/welcome_page_logo2.png
    - assets/images/welcome_page_logo2_prev_ui.png
